---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scalable-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scalable-deployment
    spec:
        containers:
          - name: scalable-pod
            image: shestera/scaletestapp
            resources:
              requests:
                memory: "10Mi"
              limits:
                memory: "20Mi"
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scalable-service
  namespace: default
  labels:
    prometheus-monitored: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: scalable-deployment
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: scalable.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scalable-service
                port:
                  number: 80

