apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scalable-service-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
spec:
  endpoints:
    - interval: 5s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prometheus-monitored: "true"